version: '3'
services:
  sbxnote_dist:
    build:
      context: .
    working_dir: /home/pwn
    container_name: sbxnote_dist
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9999"
    entrypoint: /etc/init.sh
