version: '3'
services:
  sbxnote:
    build:
      context: .
    working_dir: /home/pwn
    container_name: sbxnote
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9999"
    entrypoint: /etc/init.sh
    restart: always
