version: '3'
services:
  house_of:
    build:
      context: .
    working_dir: /home/pwn
    container_name: house_of
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9005:9999"
    entrypoint: /etc/init.sh
    restart: always
