version: '3'
services:
  festival:
    build: ./challenge/web
    container_name: festival
    ports:
      - "8017:8080"
    environment:
      - HOST=festival.ctf.zer0pts.com
      - PORT=8017
      - UWSGI_INI=/app/uwsgi.ini
      - LISTEN_PORT=8080
    restart: always
    links:
      - redis
  bot:
    build: ./challenge/bot
    container_name: disco_bot
    restart: always
    links:
      - redis
  redis:
    build: ./distfiles/redis
    restart: always
