version: '3'
services:
  party:
    build: ./challenge/web
    container_name: party
    ports:
      - "8007:8080"
    environment:
      - UWSGI_INI=/app/uwsgi.ini
      - LISTEN_PORT=8080
    restart: always
    links:
      - redis
  bot:
    build: ./challenge/bot
    container_name: disco_bot
    restart: always
    links:
      - redis
  redis:
    build: ./distfiles/redis
    restart: always
