version: '3'
services:
  modern-rome:
    build:
      context: .
    working_dir: /home/pwn
    container_name: modern-rome
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9000:9999"
    entrypoint: /etc/init.sh
    restart: always
